// <auto-generated />
using Konefeld.Kopiec.VodkaApp.DaoSqlite;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Konefeld.Kopiec.VodkaApp.DaoSqlite.Migrations
{
    [DbContext(typeof(VodkaAppDbContext))]
    [Migration("20240112224941_RemoveProducerAddress")]
    partial class RemoveProducerAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("Konefeld.Kopiec.VodkaApp.DaoSqlite.BO.Producer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CountryOfOrigin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EstablishmentYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExportStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Producers");
                });

            modelBuilder.Entity("Konefeld.Kopiec.VodkaApp.DaoSqlite.BO.Vodka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AlcoholPercentage")
                        .HasColumnType("REAL");

                    b.Property<string>("FlavourProfile")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int>("ProducerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<double>("VolumeInLiters")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ProducerId");

                    b.ToTable("Vodkas");
                });

            modelBuilder.Entity("Konefeld.Kopiec.VodkaApp.DaoSqlite.BO.Vodka", b =>
                {
                    b.HasOne("Konefeld.Kopiec.VodkaApp.DaoSqlite.BO.Producer", "ProducerImpl")
                        .WithMany()
                        .HasForeignKey("ProducerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProducerImpl");
                });
#pragma warning restore 612, 618
        }
    }
}
